import { expect, test } from '@playwright/test';
import { conversationData, nextHtml, shareUrl } from '../fixtures';

const secret = 'e2e-only-admin-secret-not-for-production-use';

test('管理端登录、全站阅读、搜索、确认删除与退出，兼容手机布局', async ({ page, context, request }, info) => {
  const created = await request.post('/api/archives/import', { headers: { 'X-Requested-With': 'Shiguang' }, data: { url: shareUrl, html: nextHtml({ ...conversationData, title: '管理端跨工作区测试对话' }) } });
  expect(created.status()).toBe(201);
  const { archive } = await created.json();
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/admin');
  await expect(page.getByRole('heading', { name: '管理每一份留存。' })).toBeVisible();
  await expect(page.locator('.admin-record')).toHaveCount(0);
  await page.getByLabel('管理密钥', { exact: true }).fill('incorrect');
  await page.getByRole('button', { name: '进入管理端' }).click();
  await expect(page.getByRole('alert')).toContainText('管理密钥不正确');
  await page.getByLabel('管理密钥', { exact: true }).fill(secret);
  await page.getByRole('button', { name: '进入管理端' }).click();
  await expect(page.getByRole('heading', { name: '全站缓存，一目了然。' })).toBeVisible();
  await expect(page.locator('.admin-record').filter({ hasText: archive.title })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: '全站缓存，一目了然。' })).toBeVisible();
  const storage = await context.storageState();
  expect(JSON.stringify(storage.origins)).not.toContain(secret);
  expect(await page.evaluate(() => document.cookie)).not.toContain('shiguang_admin');
  expect(storage.cookies.find((cookie) => cookie.name === 'shiguang_admin')?.httpOnly).toBe(true);
  const owned = await (await context.request.get('/api/archives')).json();
  expect(owned.stats.total).toBe(0);
  await page.getByLabel('搜索全站缓存').fill(archive.id);
  await page.getByRole('button', { name: '搜索', exact: true }).click();
  await expect(page.locator('.admin-record')).toHaveCount(1);
  const [reader] = await Promise.all([context.waitForEvent('page'), page.getByRole('link', { name: '阅读', exact: true }).click()]);
  await expect(reader.getByRole('heading', { name: archive.title, exact: true })).toBeVisible();
  await reader.close();
  await page.screenshot({ path: info.outputPath('admin-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.admin-record')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('admin-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: `删除缓存：${archive.title}`, exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('此操作不可撤销');
  await page.getByRole('button', { name: '再想想' }).click();
  expect((await request.get(`/api/archives/${archive.id}`)).status()).toBe(200);
  await page.getByRole('button', { name: `删除缓存：${archive.title}`, exact: true }).click();
  await page.getByRole('button', { name: '确认永久删除' }).click();
  await expect(page.getByText('没有匹配的缓存', { exact: true })).toBeVisible();
  expect((await request.get(`/api/archives/${archive.id}`)).status()).toBe(404);
  await page.getByRole('button', { name: '退出登录' }).click();
  await expect(page.getByRole('heading', { name: '管理每一份留存。' })).toBeVisible();
  expect((await context.request.get('/api/admin/archives')).status()).toBe(401);
  await page.reload();
  await expect(page.getByLabel('管理密钥', { exact: true })).toHaveValue('');
  expect(errors).toEqual([]);
});

test('会话失效清除管理数据，未配置密钥时显示部署提示', async ({ page, context }) => {
  await page.goto('/admin');
  await page.getByLabel('管理密钥', { exact: true }).fill(secret);
  await page.getByRole('button', { name: '进入管理端' }).click();
  await expect(page.getByRole('heading', { name: '全站缓存，一目了然。' })).toBeVisible();
  await expect(page.getByRole('button', { name: '刷新列表' })).toBeEnabled();
  expect((await context.request.delete('/api/admin/session', { headers: { 'X-Requested-With': 'Shiguang' } })).status()).toBe(204);
  await page.getByRole('button', { name: '刷新列表' }).click();
  await expect(page.getByRole('heading', { name: '管理每一份留存。' })).toBeVisible();
  await expect(page.locator('.admin-record')).toHaveCount(0);
  await page.route('**/api/admin/session', (route) => route.fulfill({ status: 503, json: { error: '管理端尚未启用，请在服务器配置 ADMIN_SECRET 并重启服务。', code: 'ADMIN_DISABLED' } }));
  await page.reload();
  await expect(page.getByRole('alert')).toContainText('ADMIN_SECRET');
  await expect(page.getByRole('button', { name: '进入管理端' })).toBeDisabled();
});
